#!/usr/bin/env python3 
# Ask the user for input
x = int(input("Enter an integer number: "))

# Evaluate the expression y = xx + 7x - 77x + 777x
y = x**x + 7*x - 77*x + 777*x

# Print the result
print("The value of y is:", y)
